Clarify usage or abstracts
SUSE/doc-styleguide pull request #182
Opened 2021-12-09 13:59 UTC by cwickert

This came up in the context of various bug reports about truncated chapter 'previews' both in the part overview pages and the single page HTML. Turns out the chapters lacked an abstract. We then use the first paragraph instead, but if longer than 500 (?) chars, it gets truncated.

This PR strives to give more guidance for abstracts, mainly that they are also required for chapters.

2021-12-09 14:35 UTC, cwickert commented
As agreed in today's style & language committee meeting, we should

* let the abstracts replace the 'highlight' sections. They never really worked anyways.
* limit abstracts to a number characters instead of sentences
* use a lower limit for SEO reasons: minium 70, maximum 155 chars, see https://www.contentkingapp.com/academy/meta-description/

I'll rework the PR accordingly.

2021-12-10 07:14 UTC, jfaltenbacher commented
suggests to add some info that the abstract is shown in the TOC of the parent part and in the search hitlist of any search engine in order to explain why it needs to be reduced to this certain amount of characters

2021-12-10 09:50 UTC, cwickert commented
@jfaltenbacher I'm afraid that is out of scope. 

1. Our Style Guide is already (too) long, we should keep it short and simple.
2. How abstracts are displayed in 'parents' depends on both document type (set, book, part, and article) and its parent.
3. The display might change and I don't want to touch the style guide again.
4. The 70-155 char range is explained on the website that is linked in the remark.

2021-12-13 08:15 UTC, jfaltenbacher commented
ok, thanks

2022-01-20 13:45 UTC, sknorr requested changes
Typo fixes

Also, as Jana will join today and we can talk about metadata again, I guess it makes sense not to merge before the meeting...

2022-01-20 13:45 UTC, sknorr commented on xml/docu_styleguide.outline.xml
> +      article, chapter, or set in 70&ndash;155 chracters. Do not use lists,
```suggestion
      article, chapter, or set in 70&ndash;155 characters. Do not use lists,
```

2022-01-20 13:45 UTC, sknorr commented on xml/docu_styleguide.outline.xml
> +         article, chapter, or set in 70&ndash;155 chracters. Summarize the
```suggestion
         article, chapter, or set in 70&ndash;155 characters. Summarize the
```

2022-01-20 14:44 UTC, sknorr commented on xml/docu_styleguide.outline.xml
> +      article, chapter, or set in 70&ndash;155 characters. Do not use lists,
```suggestion
      article, chapter, or set in 70&ndash;150 characters. Do not use lists,
```

2022-01-20 14:46 UTC, merged