Update of the Entities section #285
SUSE/doc-styleguide pull request #291
Opened 2024-03-20 13:00 UTC by dariavladykina

This PR aims to update the Entities section as discussed in #285.

2024-03-26 17:07 UTC, taroth21 requested changes
@dariavladykina: Many thanks for the update! 

I'm sorry it took much longer to review (and more comments) than I originally expected because the devil is in the details, as usual.

That we currently have two different setups for entity files (the new one via doc kit and that some repositories still use the old setup where all entities are defined and maintained within the respective repository) does not make it easier for the explanations in the style guide....

Let me know in case of questions (or if you need help to find examples).

2024-03-27 10:16 UTC, dariavladykina commented on xml/docu_styleguide.manage.xml
> + <screen>&lt;phrase role="productname"&gt;&amp;product;&lt;/phrase&gt; includes 389-ds.</screen>
This was my main question - whether to keep this syntax or replace it with the entities. Thank you for clarifying!

2024-03-27 10:17 UTC, dariavladykina commented on xml/docu_styleguide.manage.xml
> + Kernel since &lt;literal&gt;&amp;sle;&lt;/literal&gt; XYZ.</screen>
I believe this was the practice of working with entities in the past. Thanks for the new example!

2024-03-27 15:16 UTC, dariavladykina commented on xml/docu_styleguide.manage.xml
> -   <para>If an entity is placed at the beginning of a phrase or title, its resolved
This is a valid point, however, adding it here would demand changing this subsection's structure. Let's rather leave it under 'Acronyms' for now.

2024-03-28 15:28 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +   or <filename>entity-decl.ent</filename> in each documentation repository.</para>
```suggestion
   Find these entities in the <filename>*.ent</filename>
   files in each documentation repository. One entity file can include other entity files.</para>
```

2024-03-28 15:29 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +   or <filename>entity-decl.ent</filename> in each documentation repository.</para>
Maybe we can generalize as suggested below (by pointing to `*.ent` files).

2024-03-28 15:41 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +<screen>&lt;!ENTITY<co xml:id="co-declaration"/>product-sp<co xml:id="co-definition"/> "Code stream<co xml:id="co-value"/>"&gt;
```suggestion
<screen>&lt;!ENTITY<co xml:id="co-declaration"/>product-sp<co xml:id="co-definition"/> "1<co xml:id="co-value"/>"&gt;
```

2024-03-28 15:43 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +<screen>&lt;!ENTITY<co xml:id="co-declaration"/>product-sp<co xml:id="co-definition"/> "Code stream<co xml:id="co-value"/>"&gt;
I would use a concrete example of a service pack number here to make it clearer.

2024-03-28 15:44 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +&lt;!ENTITY productnumber "&lt;phrase xmlns='http://docbook.org/ns/docbook' role='productnumber'&gt;&lt;/phrase"&gt;<co xml:id="co-tag"/>"&gt;</screen>
```suggestion
&lt;!ENTITY productnumber "&lt;phrase xmlns='http://docbook.org/ns/docbook' role='productnumber'&gt;15&lt;/phrase"&gt;<co xml:id="co-tag"/>"&gt;</screen>
```

2024-03-28 15:45 UTC, taroth21 commented on xml/docu_styleguide.manage.xml
> +&lt;!ENTITY productnumber "&lt;phrase xmlns='http://docbook.org/ns/docbook' role='productnumber'&gt;&lt;/phrase"&gt;<co xml:id="co-tag"/>"&gt;</screen>
An entity value was still missing, I added `15` as a concrete example for a code stream number here.

2024-04-02 10:15 UTC, dariavladykina commented on xml/docu_styleguide.manage.xml
> +      If you need a new entity to be used generically across all repositories, open a pull request against <filename>generic-entities.ent</fielname> in the Doc Kit repository. After the change has be
```suggestion
      If you need a new entity to be used generically across all repositories, open a pull request against <filename>generic-entities.ent</filename> in the Doc Kit repository. After the change is approved by the Doc Kit maintainers, the entity update for <filename>generic-entities.ent</filename> will be rolled out to all Doc Kit-based repositories with the next Doc Kit run.
```

2024-04-02 10:23 UTC, dariavladykina commented on xml/docu_styleguide.manage.xml
> +      <para>Do not include custom entity definitions directly in the file header, unless the custom definitions  are needed to override externally embedded entities.
```suggestion
      <para>Do not include custom entity definitions directly in the file header, unless the custom definitions are needed to override externally embedded entities.
```

2024-04-03 06:13 UTC, janajaeger commented on xml/docu_styleguide.manage.xml
> +     <filename>entity-decl.ent</filename> file contains several categories of
What Tanja said ;)

2024-04-18 12:38 UTC, jfaltenbacher approved these changes

2024-04-18 12:50 UTC, merged