Turned style guide into book
SUSE/doc-styleguide pull request #297
Opened 2024-05-17 09:09 UTC by dariavladykina

With @tomschr 's kind help, the style guide was turned into a book (structurally) and now enjoys the 3-column layout with subsections (which we have a lot) well seen on the right.

2024-05-17 11:00 UTC, tomschr requested changes
@dariavladykina Thanks Daria, this looks great! :+1: There is only a minor issue in the DOCTYPE, see below.

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.content.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.language.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.manage.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.name.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.outline.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.smartdocs.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.structure.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.taglist.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.webwriting.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-17 11:00 UTC, tomschr commented on xml/docu_styleguide.xmlformat.xml
Also change the `sect1` in the DOCTYPE to `chapter`

2024-05-22 10:47 UTC, janajaeger approved these changes
Yayyy, finally! Thanks to the both of you!

2024-05-22 11:02 UTC, jfaltenbacher approved these changes
that is great. Looking forward to seeing the new book :)

2024-05-22 14:28 UTC, PadraigDillon1 approved these changes

2024-05-22 14:38 UTC, tomschr commented
@dariavladykina I found two files which the wrong DOCTYPE. I fixed it in commit 05e97a4. Other than that, it looks great! :+1:

2024-05-22 14:38 UTC, tomschr approved these changes

2024-05-22 14:59 UTC, merged